sudo: false
language: ruby

cache:
  bundler: true

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1 # tests on latest 2.1.x
  - 2.2.5 # tests on latest 2.2.x
  - 2.3.1
  - jruby-19mode
  - rbx-2

gemfile:
  - gemfiles/Gemfile-rails-4.0
  - gemfiles/Gemfile-rails-4.1
  - Gemfile

notifications:
  email: false
  campfire:
    on_success: change
    on_failure: always
    rooms:
      - secure: "CGWvthGkBKNnTnk9YSmf9AXKoiRI33fCl5D3jU4nx3cOPu6kv2R9nMjt9EAo\nOuS4Q85qNSf4VNQ2cUPNiNYSWQ+XiTfivKvDUw/QW9r1FejYyeWarMsSBWA+\n0fADjF1M2dkDIVLgYPfwoXEv7l+j654F1KLKB69F0F/netwP9CQ="
