language: ruby
sudo: false
cache: bundler

rvm:
  - 2.6.3
  - 2.5.3
  - ruby-head
  - jruby-head

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  include:
    - rvm: 2.2.10
      env: BRANCH=5-0-stable
    - rvm: 2.2.10
      env: BRANCH=5-1-stable
    - rvm: 2.2.10
      env: BRANCH=5-2-stable
    - rvm: 2.3.8
      env: BRANCH=5-0-stable
    - rvm: 2.2.8
      env: BRANCH=5-1-stable
    - rvm: 2.3.8
      env: BRANCH=5-2-stable
    - rvm: 2.4.5
      env: BRANCH=5-0-stable
    - rvm: 2.4.5
      env: BRANCH=5-1-stable
    - rvm: 2.4.5
      env: BRANCH=5-2-stable
    - rvm: 2.5.3
      env: BRANCH=5-0-stable
    - rvm: 2.5.3
      env: BRANCH=5-1-stable
    - rvm: 2.5.3
      env: BRANCH=5-2-stable

notifications:
  email: false
